### PR TITLE
Upgraded webpack-dev-server to 3.1.14 to fix vulnerability warning

### LINKED ISSUE #278: Warning about "high severity vulnerability" in (old?) webpack-dev-server version
When I `fastOptJS::webpack` a project using scalajs-bundler `0.14.0`, I see:

```
[error] npm notice created a lockfile as package-lock.json. You should commit this file.
[error] added 633 packages from 408 contributors and audited 5755 packages in 25.607s
[error] found 1 high severity vulnerability
[error]   run `npm audit fix` to fix them, or `npm audit` for details
```
`npm audit` from `target/scala-2.12/scalajs-bundler/main` says:

```
                       === npm audit security report ===

# Run  npm install --save-dev webpack-dev-server@3.1.14  to resolve 1 vulnerability
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Missing Origin Validation                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ webpack-dev-server [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ webpack-dev-server                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/725                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


found 1 high severity vulnerability in 5755 scanned packages
  1 vulnerability requires semver-major dependency updates.
```

`npm audit fix` says:

```
up to date in 2.591s
fixed 0 of 1 vulnerability in 5755 scanned packages
  1 package update for 1 vuln involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or do it by hand)
```

## Work-around (or perhaps fix?)

Setting:
```scala
version in startWebpackDevServer := "3.1.14",
```
in `build.sbt`, as recommended in [this sbt-scalajs-bundler scaladoc](https://github.com/scalacenter/scalajs-bundler/blob/v0.14.0/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L47-L51), seems to make the error go away, and my app bundles and runs fine, though I don't think I'm using the webpack-dev-server functionality, so it could be that that newer version breaks something.

If we can verify that the newer version works for our purposes here without any additional changes, then it should be trivial to bump [this default version in `ScalaJSBundlerPlugin`](https://github.com/scalacenter/scalajs-bundler/blob/v0.14.0/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L550).

### PR DESCRIPTION
**Pull request by andrewrembrandt**
Fixes #278

### CODE REVIEW

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala [hunk 1]
```diff
@@ -554,7 +554,7 @@ object ScalaJSBundlerPlugin extends AutoPlugin {
 
     webpackCliVersion := "2.0.11",
 
-    version in startWebpackDevServer := "2.11.1",
+    version in startWebpackDevServer := "3.1.14", //"2.11.1",
```
Comment (cquiroz) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala]: I think the latest is 3.4.1 perhaps we should directly there, and I'd remove the commented old version

**Comment by julienrf** [comment]
Thanks Andrew :)
