### PR TITLE
Read application asset name from stats

### LINKED ISSUE #111: Lots of warnings about source map URLs
Examples:

Scala 2.12.1
```
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/generic/IndexedSeqFactory.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/generic/IndexedSeqFactory.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
```

Scala.JS 0.6.14
```
[info] Cannot find source file 'https://raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalib/src/main/scala/java/util/regex/Pattern.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalib/src/main/scala/java/util/regex/Pattern.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
```

webpack prepends a `./` to everything.

### LINKED ISSUE #192: Webpack failed to create application bundle
Hi,
I am packaging some facade with scalajs-bundler. I added some config-files (to avoid using jquery): 
```js
module.exports = {
      "entry": {
    "demo-opt": [__dirname + "/bootstrapslider-opt.js"]
  },
  "output": {
    "path": __dirname,
    "filename": "[name]-bundle.js"
  },
    resolve: {
        alias: {
             "jquery": __dirname + "../../../resources/jquery-stub.js"
        }
    }
}
```
my built.sbt project is the following: 
```sbt
lazy val bootstrapslider = project.in(file("bootstrapslider")) enablePlugins (ScalaJSBundlerPlugin) settings(
  scalaJsDom,
  querki,
  npmDependencies in Compile += "bootstrap-slider" -> bootstrapSliderVersion,
  jsDependencies += ProvidedJS / "jquery-stub.js",
  webpackConfigFile := Some(baseDirectory.value / "jqueryConfig.config.js")
)
```

on a ```fullOptJS::wepack```, I get:

```sh
sbt:bootstrapslider> fullOptJS::webpack
[info] Writing scalajs.webpack.config.js
[info] Bundling the application with its NPM dependencies
[info] Hash: 8624608efa0a54f8ae83
[info] Version: webpack 3.5.5
[info] Time: 76ms
[info]              Asset     Size  Chunks             Chunk Names
[info] demo-opt-bundle.js  12.6 kB       0  [emitted]  demo-opt
[info]    [0] multi ./bootstrapslider-opt.js 28 bytes {0} [built]
[info]    [1] ./bootstrapslider-opt.js 9.27 kB {0} [built]
[info]    [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[error] java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
[error] 	at scala.Predef$.assert(Predef.scala:219)
[error] 	at scalajsbundler.Webpack$.bundle(Webpack.scala:152)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$2(WebpackTasks.scala:45)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$1(WebpackTasks.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (bootstrapslider/compile:fullOptJS::webpack) java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
```
So everything seems to be fine until this puzzling exception. In the scalajs-bundler directory/main, the jquery-stub.js file is properly copied. 

Any idea ?

### PR DESCRIPTION
**Pull request by cquiroz**
This PR aims to fix #192 and also lays some tools for future improvements.
#192 Happens because `scalajs-bundler` writes a given output file name and assumes `webpack` will produce an asset with that name. However this is not necessarily true if a custom webpack configuration is used. It would be better to ask webpack for the actual name of the asset.

On this PR the stats output of webpack is parsed to discover the actual name of the asset. The output is parsed using `play-json` and a minimal mini model is extracted. Note that the documentation on `stats` output is not totally reliable, some elements are sometimes `String` while others `Int` .

With stats we can learn what the real output file name is and use that in the plugin. In the future we can use this info to extract other useful information.

One important side effect of this. The json output takes over the regular webpack's std output, thus becoming silent which is not that nice. This PR tries to recover some of that by printing info about the build like

```
[info] [info] Version: 4.5.0
[info] [info] Hash: 06f297ae3a9e2b2b5c7d
[info] [info] Time: 1203ms
[info] [info] Built at 2018-04-11T14:03:28.254
[info] [info]
[info] [info]      Asset    Size                             Chunks
[info] [info]     app.js   11840   [emitted]   [webpack-assets-opt]
[info] [info] app.js.map   27145   [emitted]   [webpack-assets-opt]
[info] [info] index.html     179   [emitted]                     []
[info] [info]
```

This also lets me filter out warnings and thus fixes #111 

An example test is included for both `Library` and `Application` mode in `fastOptJS` and `fullOptJS`

### CODE REVIEW

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala [hunk 1]
```diff
@@ -54,20 +56,32 @@ object BundlerFile {
...
+    def project: String = application.project
 
     def targetDir: File = file.getParentFile
 
-    def asLibrary: Library =
+    def asLibrary(stats: Option[WebpackStats]): Library =
       Library(project,
               file.getParentFile.toPath
-                .resolve(Library.fileName(project))
+                .resolve(stats.flatMap(_.assetName(project)).fold(Library.fileName(project))(identity))
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: I’m wondering if we should make the `asLibrary` method return an `Option[Library]` instead. Is there a case where `assetName(project)` will fail but `Library.fileName(project)` will be *correct*?

But maybe such a change will have too many consequences and should be addressed in another PR…

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala [hunk 2]
```diff
@@ -54,20 +56,32 @@ object BundlerFile {
...
                 .toFile)
 
-    def asApplicationBundle: ApplicationBundle =
+    def asDefaultLibrary: Library =
+      Library(project,
+        file.getParentFile.toPath
+          .resolve(Library.fileName(project))
+          .toFile)
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: Would you mind adding some documentation on these methods?

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Stats.scala [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+      val Zero: AssetLine = AssetLine(Part("Asset"), Part("Size"), Part(""), Part("Chunks"))
+    }
+
+  }
+
+  final case class WebpackStats(version: String, hash: String, time: Long, errors: List[String], warnings: List[String], assets: List[Asset]) {
+
+    /**
+      * Prints to the log an output similar to what webpack pushes to stdout
+      */
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/Stats.scala]: This is awesome!

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala (hunk 1 above)
Comment (julienrf) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: Thinking again about this, I think we should return *all* the bundles produced by webpack, not just the one that has the same name as the project. What do you think?

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala [hunk 4]
```diff
@@ -185,10 +189,11 @@ object Webpack {
...
     val args = extraArgs ++: Seq("--config", configFile.absolutePath)
-    Webpack.run(args: _*)(targetDir, log)
+    val stats = Webpack.run(args: _*)(targetDir, log)
+    stats.foreach(_.print(log))
 
-    // TODO Support custom webpack config file (the output may be overridden by users)
-    val bundle = generatedWebpackConfigFile.asApplicationBundle
+    // Attempt to discover the actual name produced by webpack indexing by chunk name and discarding maps
+    val bundle = generatedWebpackConfigFile.asApplicationBundle(stats)
     assert(bundle.file.exists(), "Webpack failed to create application bundle")
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala]: I think this assertion is useless now, right?

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala [hunk 5]
```diff
@@ -185,10 +189,11 @@ object Webpack {
...
     bundle
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala]: As mentioned above, I think we should return all the bundles produced by Webpack.

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala [hunk 6]
```diff
@@ -232,25 +237,39 @@ object Webpack {
...
   }
 
+  private def jsonOutput(logger: Logger)(in: InputStream): Option[WebpackStats] = {
+
+    val parsed = Json.parse(in)
+    parsed.validate[WebpackStats] match {
+      case JsError(e) =>
+        // In case of error print the result and return None. it will be ignored upstream
+        e.foreach {
+          case (p, v) => logger.error(s"$p: ${v.mkString(",")}")
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala]: We should probably also print a first line saying that we were unable to decode the webpack output

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala [hunk 7]
```diff
@@ -1,19 +1,36 @@
...
+    var result: Option[A] = None
+    def outputCapture(o: InputStream): Unit = {
+      result = Some(outputProcess(o))
+      ()
+    }
+
     logger.debug(s"Command: ${cmd.mkString(" ")}")
     val process = Process(cmd, cwd)
-    val code = process ! toProcessLogger(logger)
+    val processIO = BasicIO.standard(false).withOutput(outputCapture).withError(toErrorLog)
```
Comment (julienrf) [inline sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala]: Maybe the `run` method of `ProcessBuilder` would be more convenient? http://scala-lang.org/api/current/scala/sys/process/ProcessBuilder.html#run(log:scala.sys.process.ProcessLogger):scala.sys.process.Process

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala (hunk 1 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: I want to export all the bundles. I'd use them for packaging, so I can define assets in webpack bun package e.g. with `sbt-native-packager`. i was thinking to do that in another PR though

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala (hunk 4 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala]: Probably, though it is still nice for testing

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala (hunk 7 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala]: i'll check `run`

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala (hunk 1 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: I've been playing a bit with this and to make a clean solution it will require some changes to the `BundleFile` hierarchy. It currently assumes it is a single file but we want to make it more flexible. I don't know if it is better to do that in another PR

**Comment by julienrf** [comment]
We can definitely do that in another PR if it's simpler!

**Comment by dispalt** [comment]
This is awesome btw, I was just trying to figure out how to make scalajs-bundler not complain because I am generating files in a different directory.

**Comment by dispalt** [comment]
Btw, this is a different way to maybe solve the same problem.

https://github.com/kossnocorp/assets-webpack-plugin

**Comment by cquiroz** [comment]
That's nice. I don't know if we want to force all users to include that plugin though.

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala (hunk 7 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/util/Commands.scala]: `run` doesn't give you access to the output stream. I think the current version is more usable

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala [hunk 8]
```diff
@@ -85,36 +96,42 @@ object BundlerFile {
...
+                          .toFile,
+                        assets)
   }
 
   /**
     * A webpack library bundle, containing only libraries
     * @param project The project the library bundle was generated for
-    * @param file The file containing the project libraries
+    * @param file The file containing the application javascript
+    * @param assets All the assets on the application
```
[the remark this answers is not in the document]
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/BundlerFile.scala]: A `Library` can have assets too. At any rate the comment is wrong. I'll revert it

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala (hunk 4 above)
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/Webpack.scala]: I expanded the assert to check each asset. This should be trivially true if webpack succeeded but I guess is good to have the asserts

File: sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/LibraryTasks.scala [hunk 9]
```diff
@@ -104,7 +104,7 @@ object LibraryTasks {
 
         }
       cachedActionFunction(monitoredFiles.to[Set])
-      generatedWebpackConfigFile.asLibrary
+      generatedWebpackConfigFile.asLibrary(None)
```
[the remark this answers is not in the document]
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/LibraryTasks.scala]: It should be possible. I'll try to fix that

[the remark this answers is not in the document]
Comment (cquiroz) [reply sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/LibraryTasks.scala]: This is going to be harder than I expected. I wonder if we could simplify the model of Library, Application, etc since webpack4 is so much faster

**Comment by cquiroz** [comment]
I think that's good. i'll start working on the feature I really want which is to export a list of assets up to sbt
